spring:
  datasource:
    url: jdbc:mysql://localhost:3306/social?useSSl=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 12301230
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema-mysql.sql
#      data-locations: classpath:db/data-mysql.sql